name: ETL Run Tests

on:
  push:
    branches:
      - main
    paths:
      - project/**
      - .github/workflows/**
  
  
jobs:
  tests:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Run Tests
        run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh


